### ISSUE TITLE
Using model checkpoint PASCAL VOC2012 and resume training

### ISSUE THREAD

**Issue by mth1996** [johnnylord/trytry-detection#4]
Hello Johnny,

thanks a lot for the great and handy implementation of Yolov3 in Pytorch. 

Code runs very well and without any problems, nevertheless I encountered a problem if I want to resume training on the PASCAL VOC2012 checkpoint. 

I don´t really know how to deal with the 78.1map_0.2treshold_PASCAL.tar file. 

In my desperation I just gave i the filepath like ".../78.1map_0.2threshold_PASCAL.tar" and I encountered the following error.

Can you help me with how to deal with these kind of files in that environment ? 

`(base) C:\Users\IKT\Documents\GitHub\YOLOv3_Masterarbeit_mth>python main.py --config config/yolov3_custom.yml
'Configuration File:'
{'agent': 'YOLOv3Agent',
 'dataloader': {'batch_size': 8, 'num_workers': 4},
 'dataset': {'anchors': [[[0.28, 0.22], [0.38, 0.48], [0.9, 0.78]],
                         [[0.07, 0.15], [0.15, 0.11], [0.14, 0.29]],
                         [[0.02, 0.03], [0.04, 0.07], [0.08, 0.06]]],
             'n_classes': 3,
             'scales': [13, 26, 52],
             'size': 416,
             'train': {'csv': 'download/CUSTOM_DATASET/train.csv',
                       'img_root': 'download/CUSTOM_DATASET/images',
                       'label_root': 'download/CUSTOM_DATASET/labels'},
             'valid': {'csv': 'download/CUSTOM_DATASET/test.csv',
                       'img_root': 'download/CUSTOM_DATASET/images',
                       'label_root': 'download/CUSTOM_DATASET/labels'}},
 'model': {'in_channels': 3, 'num_classes': 3},
 'optimizer': {'lr': 0.0001, 'weight_decay': 1e-05},
 'search': {'active': False,
            'conf_threshold': [0.2, 0.3, 0.4, 0.5],
            'nms_iou_threshold': [0.3, 0.35, 0.4, 0.45]},
 'train': {'device': 'cuda',
           'final': False,
           'logdir': 'run/yolov3_custom_baseline',
           'n_epochs': 15000,
           'resume': True},
 'valid': {'conf_threshold': 0.3, 'nms_iou_threshold': 0.45, 'when': 5}}
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main(args['config'])
  File "main.py", line 27, in main
    agent.resume()
  File "C:\Users\IKT\Documents\GitHub\YOLOv3_Masterarbeit_mth\yolov3.py", line 135, in resume
    self.model.load_state_dict(checkpoint['model'])
KeyError: 'model'`

**Comment by johnnylord** [comment]
I'm not sure where you get the "78.1map_0.2threshold_PASCAL.tar" file. 

The checkpoint loaded from "torch.load(...)" in resume method is a data structure of type "dictionary". In my training code, I will export the model weight in key 'model', optimizer in key 'optimizer', lr scheduler in 'scheduler'. You can check the `_save_checkpoint` method in training agent.

It seems that you trying to load a checkpoint file not from my implementation, and this is the reason you get tbe error.

You should try to load the checkpoint in python interactive mode, the inspect it yourself.

**Comment by mth1996** [comment]
Sorry, my bad. Of course I can´t  load an checkpoint from another repo.
Thought I had them from your repo. 

Mixed it up with that one : yolov3_voc2012.pth 

Sorry for the inconvinience!
